### ISSUE TITLE
Playstore link not working anymore

### ISSUE THREAD

**Issue by othias** [tonsV2/BloatwareRemover#1]
This seems like the only opensource system app remover for android, would be nice if we could actually install it from the playstore (maybe consider uploading it to https://f-droid.org/ too ?)

**Comment by tonsV2** [comment]
Sadly there are a few crucial bug in the app and that's why it was unpublished from the playstore. Thus I have removed the link.

**Comment by othias** [comment]
K, do you have any plans for the future?

**Comment by tonsV2** [comment]
Nothing solid. I have some ideas but I'm lacking time.
